USE [master]
GO

/****** Object:  Database [dbAutoTotalMind]    Script Date: 06.11.2018 16:45:34 ******/
DROP DATABASE [dbAutoTotalMind]
GO

/****** Object:  Database [dbAutoTotalMind]    Script Date: 06.11.2018 16:45:34 ******/
CREATE DATABASE [dbAutoTotalMind]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dbAutoTotalMind', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\dbAutoTotalMind.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'dbAutoTotalMind_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\dbAutoTotalMind_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [dbAutoTotalMind] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbAutoTotalMind].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dbAutoTotalMind] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dbAutoTotalMind] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dbAutoTotalMind] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dbAutoTotalMind] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dbAutoTotalMind] SET ARITHABORT OFF 
GO

ALTER DATABASE [dbAutoTotalMind] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dbAutoTotalMind] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dbAutoTotalMind] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dbAutoTotalMind] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dbAutoTotalMind] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dbAutoTotalMind] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dbAutoTotalMind] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dbAutoTotalMind] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dbAutoTotalMind] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dbAutoTotalMind] SET  DISABLE_BROKER 
GO

ALTER DATABASE [dbAutoTotalMind] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dbAutoTotalMind] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dbAutoTotalMind] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dbAutoTotalMind] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dbAutoTotalMind] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dbAutoTotalMind] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dbAutoTotalMind] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dbAutoTotalMind] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [dbAutoTotalMind] SET  MULTI_USER 
GO

ALTER DATABASE [dbAutoTotalMind] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dbAutoTotalMind] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dbAutoTotalMind] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dbAutoTotalMind] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [dbAutoTotalMind] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [dbAutoTotalMind] SET QUERY_STORE = OFF
GO

ALTER DATABASE [dbAutoTotalMind] SET  READ_WRITE 
GO

